name: Auto Approve Owner's PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: >-
      github.actor == github.event.repository.owner.login &&
      github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Approve pull request
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
